language: rust
sudo: false

matrix:
  include:
    - rust: nightly
      env: DESCRIPTION="cross-platform build only"
      # Redox: wait for https://github.com/rust-lang/rust/issues/60139
      install:
        - rustup target add x86_64-sun-solaris
        - rustup target add x86_64-unknown-cloudabi
        - rustup target add x86_64-unknown-freebsd
        - rustup target add x86_64-fuchsia
        - rustup target add x86_64-unknown-netbsd
        - rustup target add x86_64-unknown-redox
        - rustup target add x86_64-fortanix-unknown-sgx
        # For no_std targets
        - rustup component add rust-src
        - cargo install cargo-xbuild || true
      script:
        - cargo build --target=x86_64-sun-solaris --all-features
        - cargo build --target=x86_64-unknown-cloudabi --all-features
        - cargo build --target=x86_64-unknown-freebsd --all-features
        - cargo build --target=x86_64-fuchsia --all-features
        - cargo build --target=x86_64-unknown-netbsd --all-features
        - cargo build --target=x86_64-unknown-redox --all-features
        - cargo build --target=x86_64-fortanix-unknown-sgx --all-features
        - cargo xbuild --target=x86_64-unknown-uefi
        # also test minimum dependency versions are usable
        - cargo generate-lockfile -Z minimal-versions
        - cargo build --target=x86_64-sun-solaris --all-features
        - cargo build --target=x86_64-unknown-cloudabi --all-features
        - cargo build --target=x86_64-unknown-freebsd --all-features
        - cargo build --target=x86_64-fuchsia --all-features
        - cargo build --target=x86_64-unknown-netbsd --all-features
        - cargo build --target=x86_64-unknown-redox --all-features
        - cargo build --target=x86_64-fortanix-unknown-sgx --all-features
        - cargo xbuild --target=x86_64-unknown-uefi
  allow_failures:
    # Formatting errors should appear in Travis, but not break the build.
    - env: DESCRIPTION="Rustfmt"

before_install:
  - set -e
  - rustup self update

script:
  - cargo test
  - cargo test --examples

after_script: set +e

cache:
  cargo: true
  directories:
    - .local/share/cargo-web

before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

notifications:
  email:
    on_success: never
